### ISSUE TITLE
`launch-gnome` puts itself into an infinite loop

### ISSUE THREAD

**Issue by CompeyDev** [wjt/gnome-desktop-on-wsl#1]
Looks like the launch-gnome script attempts to check whether the `INSIDE_GENIE` environment variable is true. If not, it tries to launch using Genie. Ideally the variable should return try inside a Genie command -- but it doesn't. 

As a result it infinitely loops trying to run the genie command over and over again. 

Find below a screenshot:

<img src="https://user-images.githubusercontent.com/74418041/204478230-7f65ee4f-3f87-45b2-a665-da25886d69dc.png" width=50% />

**Comment by wjt** [comment]
Thanks. I'm no longer working on this repo – it was a one-week experiment. I will archive it. Feel free to fork if it is useful to you.

Specifically the genie bit is probably superseded by https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/.
